---
title: "My Dashboard"
subtitle: "Quick Access to Services"
logo: "assets/logo.png"
header:
  - name: "Home"
    logo: "assets/logo.png"
    url: "http://localhost:8085"
    target: "_self"

services:
  - name: "Portainer"
    logo: "assets/portainer.png"
    url: "https://localhost:9443"
    target: "_blank"
    subtitle: "Manage your Docker containers"
  
  - name: "Rancher"
    logo: "assets/rancher.png"
    url: "https://localhost"
    target: "_blank"
    subtitle: "Orchestrate your Kubernetes clusters"
  
  - name: "GitBucket"
    logo: "assets/gitbucket.png"
    url: "http://localhost:8080"
    target: "_blank"
    subtitle: "Self-hosted Git server"
  
  - name: "Headscale"
    logo: "assets/headscale.png"
    url: "http://localhost:3014"
    target: "_blank"
    subtitle: "TailScale coordination server"
  
  - name: "Headscale UI"
    logo: "assets/headscale-ui.png"
    url: "http://localhost:50000"
    target: "_blank"
    subtitle: "Headscale management UI"
  
  - name: "Jellyfin"
    logo: "assets/jellyfin.png"
    url: "http://localhost"
    target: "_blank"
    subtitle: "Media server"

# Optional static links
static:
  - name: "Documentation"
    logo: "assets/docs.png"
    url: "https://docs.example.com"
    target: "_blank"
    subtitle: "Project Documentation"
    
# Theme and appearance settings
theme: "default"
search:
  placeholder: "Search..."
  engines:
    - name: "Google"
      url: "https://www.google.com/search?q={query}"
    - name: "DuckDuckGo"
      url: "https://duckduckgo.com/?q={query}"
