---
version: '3'

services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  rancher:
    image: rancher/rancher
    privileged: true
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      CATTLE_BOOTSTRAP_PASSWORD: "Password1234"
      
volumes:
#  wordpress-db:
  portainer_data:

gitbucket:
  image: gitbucket/gitbucket:latest
  container_name: gitbucket
  restart: unless-stopped
  ports:
    - "8080:8080"
  volumes:
     - gitbucket_data:/gitbucket
  environment:
     GITBUCKET_PORT: 8080
     GITBUCKET_HOME: /gitbucket
 Volumes:
  gitbucket_data:
