---
version: '3'

services:
  gitbucket:
    image: gitbucket/gitbucket:latest
    container_name: gitbucket
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - gitbucket_data:/gitbucket
    environment:
      GITBUCKET_PORT: 8080
      GITBUCKET_HOME: /gitbucket

  bookstack:
    image: solidnerd/bookstack:latest
    container_name: bookstack
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - bookstack_data:/var/www/bookstack
    environment:
      DB_HOST: db
      DB_DATABASE: bookstack
      DB_USERNAME: bookstack_user
      DB_PASSWORD: strongpassword

    bookstack-db:
    image: mariadb:10.5
    container_name: bookstack-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookstack
      MYSQL_USER: bookstack_user
      MYSQL_PASSWORD: strongpasswor
      
volumes:
  gitbucket_data:
  bookstack_data:
  bookstack_db_data:
