version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  rancher:
    image: rancher/rancher
    privileged: true
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      CATTLE_BOOTSTRAP_PASSWORD: "Password1234"

  gitbucket:
    image: gitbucket/gitbucket:latest
    container_name: gitbucket
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - gitbucket_data:/gitbucket
    environment:
      GITBUCKET_PORT: 8080
      GITBUCKET_HOME: /gitbucket
  
  homer:
    image: b4bz/homer:latest
    container_name: homer
    ports:
      - "8085:8080" # Maps the container's port 8080 to the host's port 8085
    volumes:
      - ./homer/config.yml:/www/assets/config.yml:ro # Bind mount for configuration
      - ./homer/assets:/www/assets/icons:ro # Bind mount for logos and assets
    restart: unless-stopped # Automatically restart the container unless manually stopped
    environment:
      TITLE: "My Dashboard"
      SUBTITLE: "Quick Access to Services"

  headscale:
    image: headscale/headscale:stable
    container_name: headscale
    volumes:
      - /etc/headscale/config:/etc/headscale
      - ./container-data/data:/var/lib/headscale
    ports:
      - 3014:8080
      - 9090:9090
    command: serve
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"   # Limit to 0.5 CPUs
          memory: "512M" # Limit to 512MB RAM

  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    container_name: headscale-ui
    ports:
      - 50000:8080
    restart: unless-stopped

  
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - ./data:/var/lib/registry

  postgresql:
    image: postgres:16
    hostname: postgresql # Explicit hostname for resolution
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_DB=keycloak
      - POSTGRES_PASSWORD=SUPERsecret
    volumes:
      - '/home/ubuntu/docker/keycloak/postgresql_data:/var/lib/postgresql/data'
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    restart: always
    command: start
    depends_on:
      - postgresql
    environment:
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=SUPERsecret
      - KC_DB_URL_HOST=postgresql # Matches the hostname of the PostgreSQL service
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - "3002:8080" # Expose Keycloak's HTTP port on localhost
    networks:
      - keycloak_network

networks:
  keycloak_network:
    driver: bridge

volumes:
  portainer_data:
  gitbucket_data:
  postgres_data:
  homer-config:
    driver: local
