version: '3'

services:
  gitbucket:
    image: gitbucket/gitbucket:latest
    container_name: gitbucket
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - gitbucket_data:/gitbucket
    environment:
      GITBUCKET_PORT: 8080
      GITBUCKET_HOME: /gitbucket

  bookstack:
    image: solidnerd/bookstack:latest
    container_name: bookstack
    restart: unless-stopped
    depends_on:
      - bookstack-db
    ports:
      - "8081:80"
    volumes:
      - bookstack_data:/var/www/bookstack
    environment:
      DB_HOST: bookstack-db
      DB_DATABASE: bookstack
      DB_USERNAME: bookstack_user
      DB_PASSWORD: strongpassword
      APP_KEY: base64:h2WGIUhzRFgZKui1QUQPzNgNa6XE3ptpmYNQ0DHDOUY=
      APP_URL: http://localhost:8081

  bookstack-db:
    image: mariadb:10.5
    container_name: bookstack-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookstack
      MYSQL_USER: bookstack_user
      MYSQL_PASSWORD: strongpassword
    volumes:
      - bookstack_db_data:/var/lib/mysql

volumes:
  gitbucket_data:
  bookstack_data:
  bookstack_db_data:
