---
version: '3'

services:
  gitbucket:
    image: gitbucket/gitbucket:latest
    container_name: gitbucket
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - gitbucket_data:/gitbucket
    environment:
      GITBUCKET_PORT: 8080
      GITBUCKET_HOME: /gitbucket

  bookstack:
    image: solidnerd/bookstack:latest
    container_name: bookstack
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - bookstack_data:/var/www/bookstack
    environment:
      DB_HOST: db
      DB_DATABASE: bookstack
      DB_USERNAME: bookstack_user
      DB_PASSWORD: strongpassword

volumes:
  gitbucket_data:
  bookstack_data:
