version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  rancher:
    image: rancher/rancher
    privileged: true
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      CATTLE_BOOTSTRAP_PASSWORD: "Password1234"

  gitbucket:
    image: gitbucket/gitbucket:latest
    container_name: gitbucket
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - gitbucket_data:/gitbucket
    environment:
      GITBUCKET_PORT: 8080
      GITBUCKET_HOME: /gitbucket
  
  homer:
    image: b4bz/homer:latest
    container_name: homer
    ports:
      - "8085:8080" # Maps the container's port 8080 to the host's port 8085
    volumes:
      - ./homer/config:/www/assets # Bind mount for configuration
    restart: unless-stopped # Automatically restart the container unless manually stopped

  headscale:
    image: headscale/headscale:stable
    container_name: headscale
    volumes:
      - /etc/headscale/config:/etc/headscale
      - ./container-data/data:/var/lib/headscale
    ports:
      - 3014:8080
      - 9090:9090
    command: serve
    restart: unless-stopped
  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    container_name: headscale-ui
    ports:
      - 50000:8080


volumes:
  portainer_data:
  gitbucket_data:
  homer-config:
    driver: local
